### ISSUE TITLE
Comments on Plot class

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#39]
- Is the hard-coded value in `Plot.set_bin_ticks` (`11250`) supposed to be Nyquist? If so, shouldn't it be `11025`?
- Documentation for the `max_time` keyword argument should be added to `Plot.log_envelop`.
- Doesn't the slicing `self.parent.fft()[:last_index]` in `Plot.fft` discard the final frequency bin when `last_index = -1`?
- In `Plot.time_damping`, `second_index` is not offset by `first_index`, leading to incorrect damping curve and signal envelope.
- Is it common to have a logarithmic time axis when analyzing these features, or is that something that is original to this package?

Here are some comments about the plots themselves:
- There is some inconsistency with respect to axis labels. Some are capitalized (e.g. `Plot.peak_damping`, `SoundPack.compare_peaks`). Some are in French (e.g. `Plot.fft_hist`, `Plot.peaks`, `SoundPack.fft_mirror`, `SoundPack.fft_diff`, `SoundPack.coherence_plot`). Some do not contain units (e.g. `Plot.fft`). Some contain no labels (e.g. `Sound.bin_hist`, `SoundPack.bin_power_hist`).
- Use of transparency (`alpha`) or deliberate ordering of plot calls could improve some line plots (e.g. `Plot.time_damping`, `Plot.timbre`).
- Use of negative Y-axis values was initially confusing to me in plots like `SoundPack.compare_peaks`, `SoundPack.fft_mirror` and `SoundPack.integral_compare`. I think it might be more clear if you simply mirror the positive-valued ticks.
- I think the use of exponential notation is unnecessary in `SoundPack.compare_peaks` and `SoundPack.fft_mirror`.
- I believe, wherever possible, the use of decibels (dB) for Y-axis units would be better. In general, "amplitude" and "power" can be quite vague as Y-axis labels, especially when no units are provided.

**Comment by olivecha** [comment]
Issues with the `Plot` class
- changed the max bin frequency to Nyquist
- Replaced -1 with length of the frequency array
- Added the offset corresponding to `first_index` in `Plot.time_damping`
- The logarithmic time scale is original to this package and helps analyzing differences in onset behaviour

**Comment by olivecha** [comment]
Issues with the plot themselves
- Added normalized and mirror mention in `integral_compare`
- Made axis labels uniform (uncapitalized english)
- Added (normalized) mention when no units
- Added missing axis labels
- Cosmetic changes to `plot_damping`
- Added mirror mention to plots with mirror y-axis
- The exponential notation in `compare_peaks` and `fft_mirror` is an artefact of the symlog scale, I could override it if you think it's necessary, however this is consistent with the log scale in `Plot.fft` and `Plot.peaks`.
- I have not added dB mention to y-axis labels because all values with "amplitude" were or should have been normalized.
