### ISSUE TITLE
Comments on SoundPack class

### ISSUE THREAD

**Issue by cwitkowitz** [olivecha/guitarsounds#40]
- Wouldn’t `Sound.bin_divide` in `SoundPack.equalize_time` be more appropriate in `SoundPack.__init__`? And shouldn't it be called even if `equalize_time=False`?
- The methodology for rejecting signals in `SoundPack.combine_envelope` seems a little odd. The point-wise average of all envelopes is computed and the summed point-wise deviation from each average is compared to the average of summed point-wise deviations in order to make this assessment. Won't this procedure always reject half of the sounds?
- There are instances of calls to `Signal.plot` in `SoundPack.combine_envelope` that break execution. I believe these should be calls to `Signal.old_plot` instead.
- There are also some attempts to access the `.bins` attribute of signals in `SoundPack.combine_envelope` that break execution because they are invoked on an array of sounds rather than a particular `Signal` instance.
- Why are the mean peak distances computed in `SoundPack.compare_peaks` divided by 4?
- Why does `SoundPack.compare_peaks` lower `difference_threshold` until at least one group of different peaks is established? Why is it necessary to display at least one such group?
- The documentation in `SoundPack.fft_diff` is incorrect for the bins parameter. Change `True` to `‘bins’`.

**Comment by olivecha** [comment]
- `Sound.bin_divide` is already called in `Sound.condition`, so there is no need to call it in `SoundPack.__init__`, however `SoundPack.equalize_time` changes the signal attribute of the `Sound` instances which is used in `Sound.bin_divide`, so it has to be called again when the sounds are trimmed. However, I've moved the conditioning of `Sound` instances if the `SoundPack` is instantiated using `Sound` instances outside of the `equalize_time=True` branch.
- `combine_envelop` was an experimental feature and was removed as it was not deemed useful in analyzing sounds.
- The 0.25 factor is to make sure the value of `peak_distance` is actually smaller than the real distance between peaks but larger than a possible small difference between corresponding peaks for two sounds. So if the note A = 110 Hz is played on two guitars, but one is slightly detuned so that A = 112Hz the `peak_distance` would be about `110 / 4 = 27.5`, so the peaks at 110 Hz and 112 Hz would be aligned together while ensuring that peaks at 110 Hz and 220 Hz would not be aligned together.
- The goal of the method is to find the peaks having the largest difference. However, I added a `break` if the `difference_threshold` gets close to zero and the possibility of plotting the matched peak without specifying different peaks.
- I've corrected the docstring for `SoundPack.fft_diff`
