### ISSUE TITLE
No `timbre` method

### ISSUE THREAD

**Issue by ebezzam** [olivecha/guitarsounds#47]
When running the demo notebook, I get the following error when running `mysound.plot.timbre(label='regular')`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [30], in <cell line: 5>()
      1 # # Timbral attributes not loud
      2 # mysound.plot.timbre(label='regular')
      3 
      4 # Timbral attributes loud
----> 5 mysound.signal.normalize().plot.timbre(label='louder')
      7 # add labels to the legend 
      8 guitarsounds.plt.legend()

AttributeError: 'Plot' object has no attribute 'timbre'
```

It seems like there is no `timbre` method for the [`Plot`](https://github.com/olivecha/guitarsounds/blob/edc3c05e0cf508c10956f611157070cb3bbac0a3/guitarsounds/analysis.py#L1561) object.

**Comment by olivecha** [comment]
Hi, 
The `timbre` method was removed at one point as it was not particularly useful in evaluating sounds in the lutherie domain (not a lot meaningful comparisons could be obtained because the underlying timbre tool was meant to compare sounds with stronger differences).

commit 3b98e1c6febbac585fd91aa20128a1952365387f solved the issue

Thanks,

Olivier
